### PR TITLE
first.replay.io v2

### PR DESCRIPTION
**Pull request by jonbell-lot23**
**Summary**

The goals in this redesign are:

1. We want the page to feel more branded and nice
2. We want the code to be more interesting, so there's something to investigate in DevTools
3. It's important that "jump to code" and the console both point to interesting things

**Not part of this PR because lower priority**

1. Not going to detect Replay browser, we can assume people get here from our landing page
2. No links to docs, contact, etc -- want to keep the page copy as light as possible
3. We don't need to make the code perfect, and we don't need to bikeshed the exact design/copy too much, which has the tendency to take a ton of time because it's so subjective. We should bias towards getting this out, then we can always do a follow-up to address finer points of the approach. The key is replacing the current uninspired design as fast as possible.

**Reviewer guidance**

Hello, reviewers! Thanks for taking a look at a nicer first.replay.io. [Here's a quick loom](https://www.loom.com/share/81e63c4bb9474d43865681ac6743f4a2) of the process I've used to do QA on this page.

If you have copy suggestions, feel free to see the full flow [here](https://www.notion.so/replayio/first-replay-io-3c21962d406d4ee5a1a01379b336dd5f?pvs=4) and add suggested edits.

**Old**
image

**New**
image

### CODE REVIEW

**Comment by jonbell-lot23** [comment]
Latest Loom showing the experience: https://www.loom.com/share/25c33934f030489abce27cf40ea3c3da

**Comment by jonbell-lot23** [comment]
Loom confirming that jump to code and time traveling in the console take people to good places:
https://www.loom.com/share/daa999ca765f494db06839beeb05b43a

(Unsurprising because we still have logrocket turned off)

**Review by jcmorrow — APPROVED** [review]
👍

**Comment by jonbell-lot23** [comment]
Hi @jasonLaster ! Just want to call out the elephant in the room that I mentioned in the description: of course we can change copy, add more bling, try to make the code more interesting, etc. But I think this is a solid improvement on the current version of first.replay.io, so I'd like to get this out ASAP (minor copy changes welcome of course!) and then we can always push the design further in follow-ups. "Done is the engine of more!"

**Review by jazzdan — APPROVED** [review]
Cool! Love it

**Pull request merged**
